### ISSUE TITLE
update outdated template-operator document

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/template-operator#100]
The [Bundling and installation](https://github.com/kyma-project/template-operator#bundling-and-installation) in template operator document is outdated, which affects kyma module hands-on experience. We got issue reported [here](https://github.com/kyma-project/template-operator/issues/96).

AC:
- [ ] describe Kyma CLI `alpha create module` with module config to build moduletemplate (i.e. https://github.com/kyma-project/template-operator?tab=readme-ov-file#build-and-push-your-module-to-the-registry)
- [ ] describe kyma CLI `disable module`, `enable module` to control module in [Using your module in the Lifecycle Manager ecosystem](https://github.com/kyma-project/template-operator#using-your-module-in-the-lifecycle-manager-ecosystem)
- [ ] check and update other outdated part

**Comment by jeremyharisch** [comment]
Duplicate from #90
