### ISSUE TITLE
Decoupling of the referenced helm chart

### ISSUE THREAD

**Issue by DimitarHKostov** [kyma-project/template-operator#13]
**Description**

The helm chart for the component being installed and managed  is tightly-coupled(hardcoded). It would be helpful if it can be referenced via url.

**Reasons**

This way the need for double-maintanance of the helm chart will be eliminated.

**Comment by jakobmoellersap** [comment]
This requirement was rejected multiple times because we discourage the soft references via url. This can be bad because the content behind the URL might change or get removed. This is a problem because suddenly your module version is broken without you realising it. Thus I am closing this issue and we will not pursue this.

**Comment by manolvalchev** [comment]
> we discourage the soft references via url.
The fundamental point in the request is to allow reference of charts (resources in general) from an external repo and not force people to produce duplicate charts (resources in general) in many repos. What problem do you see in referencing a released charts (resources in general), e.g. version 1.2.3?

**Comment by jakobmoellersap** [comment]
By referencing released charts in URLs you have to make sure the URL is always available and usable. While this is ensured by bundling it into the Module with the kyma CLI, we cannot ensure these guarantees when you are using external references. They are fundamentally not part of our integrity guarantees that we deliver when bundling the chart via OCI image layer. If this is acceptable to you I suggest we add an unsafe mode instead that we can enable and then also support more layer types with external references. WDYT?

**Comment by jakobmoellersap** [comment]
I want to emphasise that you do not need double maintenance to correctly bundle your module. Instead you just should not check it out into the operator repository but pull it in a make target. that way during bundling you will still ensure one unique chart version while you can maintain your chart elsewhere.
