### ISSUE TITLE
Migrate release-template-operator-assets prowjob out of Neighbor's Prow

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/template-operator#159]
**Description**
 In the release-template-operator-assets prow job we upload the assets to the GCP project Kyma-project artifact registry, so there should be access to the template operator GitHub Actions.

There is a [ticket](https://github.com/kyma-project/test-infra/issues/9925) for the neighbors to provide the correct access.

**Attachments**

**Comment by janmedrek** [comment]
Closing in favor of: https://github.com/kyma-project/lifecycle-manager/issues/1811
