### ISSUE TITLE
Release the Module Template and Manifest

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/template-operator#52]
**Description**

It would be great to have the Module Template and manifest (k8s yamls) released for the Template Operator. It will make it easier to present/use the example in various tutorials, documents, or guides.

Keda Manager, BTP Manager and eventing-manager already have their pipelines built, this can be a starting point for this implementation.

**Acceptance Criteria**
- [x] GH actions pipeline built
- [x] ModuleTemplate available in GH release (0.1.2)
- [x] Default CR available in GH release (0.1.2)
- [x] K8S manifests available in GH release (0.1.2)
- [x] (stretch) include module-config file for the CLI build command

**Reasons**

It will be much easier to just download the Module Template and Manifest instead of building it locally.

**Comment by LeelaChacha** [comment]
0.1.2 released with the assets mentioned in the issue

**Comment by jeremyharisch** [comment]
https://github.com/kyma-project/template-operator/releases/tag/0.1.2
